### ISSUE TITLE
Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

### ISSUE THREAD

**Issue by joudinet** [processone/p1_oauth2#3]
Compiling with OTP 20.0, I get the following warning:
src/oauth2_token.erl:68: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

This is just for your information. Fee free to close this issue.

**Comment by badlop** [comment]
Right. I've applied some fixes from the upstream kivra repository, and one of them fix that: https://github.com/processone/p1_oauth2/commit/bd8c83ff4d689015d0453834164bb8722721c66a
